import { Injectable } from '@nestjs/common';
import { DatabaseService } from '../../../database/database.service';
import { StrategyEntity } from '../../../database/types';
import { AiStrategyDomain } from '../ai-strategy.types';

// Postgres error code for a unique-constraint violation, raised by
// `uk_strategies_name_version` (global unique on (name, version) — shared
// with SYSTEM/USER strategies, see the comment on createVersion below).
const UNIQUE_VIOLATION = '23505';
const MAX_VERSION_INSERT_ATTEMPTS = 5;

@Injectable()
export class AiStrategyRepository {
  constructor(private readonly database: DatabaseService) {}

  /**
   * Every AI-generated strategy this user owns. Ownership scoping lives in
   * the WHERE clause (owner_user_id = $1 AND type = 'AI_GENERATED'), not in
   * a post-filter — a caller cannot see another user's AI strategies by
   * trimming a larger result later. See ai-strategy.service.spec.ts for the
   * regression test that fails if this scoping is ever removed.
   */
  async listMine(userId: string): Promise<StrategyEntity[]> {
    const result = await this.database.query<StrategyEntity>(
      `SELECT * FROM strategies WHERE type = 'AI_GENERATED' AND owner_user_id = $1 ORDER BY created_at DESC`,
      [userId],
    );
    return result.rows;
  }

  async findMineById(id: string, userId: string): Promise<StrategyEntity | null> {
    const result = await this.database.query<StrategyEntity>(
      `SELECT * FROM strategies WHERE id = $1 AND type = 'AI_GENERATED' AND owner_user_id = $2`,
      [id, userId],
    );
    return result.rows[0] ?? null;
  }

  /**
   * Ownership-scoped, deduplicated to the highest version per name — the
   * set Strategy Search's catalog offers for combination (task-15). Every
   * version is still an immutable row addressable by id (see
   * findMineById/createVersion's doc comment); this only picks which one
   * is "the current AI strategy of this name" for selection purposes.
   */
  async listLatestPerName(userId: string): Promise<StrategyEntity[]> {
    const result = await this.database.query<StrategyEntity>(
      `SELECT DISTINCT ON (name) *
       FROM strategies
       WHERE type = 'AI_GENERATED' AND owner_user_id = $1 AND is_active = true
       ORDER BY name, version DESC`,
      [userId],
    );
    return result.rows;
  }

  /**
   * Ownership + active-scoped lookup by id, used when resolving an
   * "AI:<strategyId>" search-strategy type back to its row (see
   * StrategySearchService.start()). Returns null rather than throwing so
   * the caller can produce a clear 400 instead of a 404 from deep inside
   * strategy resolution.
   */
  async findOwnedActiveById(id: string, userId: string): Promise<StrategyEntity | null> {
    const result = await this.database.query<StrategyEntity>(
      `SELECT * FROM strategies WHERE id = $1 AND type = 'AI_GENERATED' AND owner_user_id = $2 AND is_active = true`,
      [id, userId],
    );
    return result.rows[0] ?? null;
  }

  /**
   * Always INSERTs a new row — never an UPDATE over history, same rule as
   * StrategyRepository.createVersion (strategy-search/repositories), whose
   * versioning behavior this reuses.
   *
   * Version numbers are global-next-per-name (MAX(version) WHERE name=$1,
   * not scoped by owner), because `strategies.(name, version)` is a single
   * global unique index shared with SYSTEM/USER rows — the same reason the
   * existing StrategyRepository does it this way. A consequence: if another
   * user already saved an AI strategy under the same name, a fresh save
   * here does not necessarily start at version 1 — it continues the shared
   * numbering for that name instead of colliding with it.
   */
  async createVersion(
    userId: string,
    name: string,
    sourceCode: string,
    domain: AiStrategyDomain,
  ): Promise<StrategyEntity> {
    for (let attempt = 0; attempt < MAX_VERSION_INSERT_ATTEMPTS; attempt++) {
      try {
        return await this.database.withTransaction(async (client) => {
          const maxVersionResult = await client.query<{ next_version: number }>(
            `SELECT COALESCE(MAX(version), 0) + 1 AS next_version FROM strategies WHERE name = $1`,
            [name],
          );
          const nextVersion = maxVersionResult.rows[0].next_version;

          const insertResult = await client.query<StrategyEntity>(
            `INSERT INTO strategies
               (owner_user_id, name, type, version, description, language, source_code, parameters, is_active)
             VALUES ($1, $2, 'AI_GENERATED', $3, $4, 'PYTHON', $5, $6::jsonb, true)
             RETURNING *`,
            [
              userId,
              name,
              nextVersion,
              'Generated by AI Strategy from a natural-language prompt.',
              sourceCode,
              JSON.stringify({ domain }),
            ],
          );
          return insertResult.rows[0];
        });
      } catch (error: unknown) {
        const isUniqueViolation =
          typeof error === 'object' &&
          error !== null &&
          'code' in error &&
          (error as { code?: string }).code === UNIQUE_VIOLATION;
        if (!isUniqueViolation || attempt === MAX_VERSION_INSERT_ATTEMPTS - 1) {
          throw error;
        }
        // Another concurrent save for the same name took this version
        // number — loop and retry with a freshly recomputed next version.
      }
    }
    throw new Error(`Failed to create a new AI strategy version of "${name}" after ${MAX_VERSION_INSERT_ATTEMPTS} attempts.`);
  }
}
