CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ============================================================
-- 1. SESSIONS
-- ============================================================
CREATE TABLE IF NOT EXISTS sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    last_seen_at TIMESTAMPTZ
);

-- ============================================================
-- 2. CANDLES (TimescaleDB Hypertable)
-- Shared market data for Binance BTCUSDT
-- ============================================================
CREATE TABLE IF NOT EXISTS candles (
    timeframe VARCHAR(10) NOT NULL,
    timestamp TIMESTAMPTZ NOT NULL,
    open NUMERIC(30, 12) NOT NULL,
    high NUMERIC(30, 12) NOT NULL,
    low NUMERIC(30, 12) NOT NULL,
    close NUMERIC(30, 12) NOT NULL,
    volume NUMERIC(30, 12) NOT NULL,
    PRIMARY KEY (timeframe, timestamp)
);

SELECT create_hypertable(
    'candles',
    'timestamp',
    if_not_exists => TRUE
);

-- ============================================================
-- 3. STRATEGIES
-- Immutable strategy parameters per version
-- ============================================================
CREATE TABLE IF NOT EXISTS strategies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    version INT NOT NULL,
    type VARCHAR(50) NOT NULL,
    parameters JSONB NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_strategies_session_name_version UNIQUE (session_id, name, version)
);

CREATE INDEX IF NOT EXISTS idx_strategies_session_id ON strategies(session_id);

-- ============================================================
-- 4. EXPERIMENTS
-- Search / Backtest run specification
-- ============================================================
CREATE TABLE IF NOT EXISTS experiments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    timeframe VARCHAR(10) NOT NULL,
    start_time TIMESTAMPTZ NOT NULL,
    end_time TIMESTAMPTZ NOT NULL,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    completed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_experiments_session_id ON experiments(session_id);
CREATE INDEX IF NOT EXISTS idx_experiments_session_created ON experiments(session_id, created_at);

-- ============================================================
-- 5. EXPERIMENT_STRATEGIES
-- Mapping between experiments and strategy candidates
-- ============================================================
CREATE TABLE IF NOT EXISTS experiment_strategies (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    experiment_id UUID NOT NULL REFERENCES experiments(id) ON DELETE CASCADE,
    strategy_id UUID NOT NULL REFERENCES strategies(id) ON DELETE CASCADE,
    status VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_exp_strat_experiment_strategy UNIQUE (experiment_id, strategy_id)
);

CREATE INDEX IF NOT EXISTS idx_exp_strat_experiment_id ON experiment_strategies(experiment_id);
CREATE INDEX IF NOT EXISTS idx_exp_strat_strategy_id ON experiment_strategies(strategy_id);

-- ============================================================
-- 6. TRADES
-- Simulated trades generated by backtesting a candidate strategy
-- ============================================================
CREATE TABLE IF NOT EXISTS trades (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    experiment_strategy_id UUID NOT NULL REFERENCES experiment_strategies(id) ON DELETE CASCADE,
    side VARCHAR(10) NOT NULL,
    entry_time TIMESTAMPTZ NOT NULL,
    entry_price NUMERIC(30, 12) NOT NULL,
    stop_loss NUMERIC(30, 12),
    take_profit NUMERIC(30, 12),
    exit_time TIMESTAMPTZ,
    exit_price NUMERIC(30, 12),
    quantity NUMERIC(30, 12),
    profit_loss NUMERIC(30, 12),
    return_percent NUMERIC(20, 10),
    exit_reason VARCHAR(50),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_trades_exp_strat_id ON trades(experiment_strategy_id);
CREATE INDEX IF NOT EXISTS idx_trades_entry_time ON trades(entry_time);
CREATE INDEX IF NOT EXISTS idx_trades_exit_time ON trades(exit_time);

-- ============================================================
-- 7. EVALUATIONS
-- Performance metrics for an evaluated strategy candidate
-- ============================================================
CREATE TABLE IF NOT EXISTS evaluations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    experiment_strategy_id UUID NOT NULL UNIQUE REFERENCES experiment_strategies(id) ON DELETE CASCADE,
    total_return NUMERIC(20, 10),
    profit_loss NUMERIC(30, 12),
    win_rate NUMERIC(10, 6),
    max_drawdown NUMERIC(20, 10),
    number_of_trades INT NOT NULL DEFAULT 0,
    profit_factor NUMERIC(20, 10),
    sharpe_ratio NUMERIC(20, 10),
    overall_score NUMERIC(20, 10),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_evaluations_overall_score ON evaluations(overall_score);

-- ============================================================
-- 8. LEADERBOARDS
-- Session personal or system global leaderboards
-- ============================================================
CREATE TABLE IF NOT EXISTS leaderboards (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    session_id UUID NOT NULL REFERENCES sessions(id) ON DELETE CASCADE,
    name VARCHAR(255) NOT NULL,
    type VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_leaderboards_session_id ON leaderboards(session_id);
CREATE INDEX IF NOT EXISTS idx_leaderboards_session_type ON leaderboards(session_id, type);

-- ============================================================
-- 9. LEADERBOARD_ENTRIES
-- Ranked strategy entries in a leaderboard
-- ============================================================
CREATE TABLE IF NOT EXISTS leaderboard_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    leaderboard_id UUID NOT NULL REFERENCES leaderboards(id) ON DELETE CASCADE,
    experiment_strategy_id UUID NOT NULL REFERENCES experiment_strategies(id) ON DELETE CASCADE,
    rank INT NOT NULL,
    score NUMERIC(20, 10) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    CONSTRAINT uq_lb_entries_lb_rank UNIQUE (leaderboard_id, rank),
    CONSTRAINT uq_lb_entries_lb_exp_strat UNIQUE (leaderboard_id, experiment_strategy_id)
);

CREATE INDEX IF NOT EXISTS idx_lb_entries_leaderboard_id ON leaderboard_entries(leaderboard_id);
CREATE INDEX IF NOT EXISTS idx_lb_entries_exp_strat_id ON leaderboard_entries(experiment_strategy_id);
